# -*- coding: utf-8 -*-
import pyshorteners
from PyQt5 import QtCore, QtGui, QtWidgets
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 322)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, 0, 1366, 41))
        font = QtGui.QFont()
        font.setFamily("Particle")
        font.setPointSize(24)
        self.label.setFont(font)
        self.label.setStyleSheet("color: white; background: #221F1F;")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(60, 120, 1241, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        self.lineEdit.setFont(font)
        self.lineEdit.setStyleSheet("color: white; background: #221F1F; border: 0px solid white;")
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(60, 260, 1241, 41))
        font = QtGui.QFont()
        font.setFamily("Century Gothic")
        font.setPointSize(15)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setStyleSheet("color: white; background: #221F1F; border: 0px solid white;")
        self.lineEdit_2.setPlaceholderText("Here is a shotened link")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(70, 60, 1221, 41))
        font = QtGui.QFont()
        font.setFamily("Particle")
        font.setPointSize(22)
        self.pushButton.setFont(font)
        self.pushButton.setStyleSheet("color: white; background: #221F1F; border: 0px solid white;")
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(70, 180, 1221, 61))
        font = QtGui.QFont()
        font.setFamily("Particle")
        font.setPointSize(35)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setStyleSheet("color: white; background: #221F1F; border: 0px solid white;")
        self.pushButton_2.setObjectName("pushButton_2")
        MainWindow.setCentralWidget(self.centralwidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.func()
    def func(self):
        self.pushButton.clicked.connect(self.exit)
        self.pushButton_2.clicked.connect(self.shortened)
    def exit(self):
        exit()
    def shortened(self):
        obj = pyshorteners.Shortener()
        self.lineEdit_2.setText(obj.tinyurl.short(self.lineEdit.text()))
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "L-Shotener 0.0.1"))
        self.label.setText(_translate("MainWindow", "                                                                  -  link shortener -"))
        self.lineEdit.setPlaceholderText(_translate("MainWindow", "Write link for shorting..."))
        self.pushButton.setText(_translate("MainWindow", "EXIT"))
        self.pushButton_2.setText(_translate("MainWindow", "Short"))
import sys
app = QtWidgets.QApplication(sys.argv)
MainWindow = QtWidgets.QMainWindow()
ui = Ui_MainWindow()
ui.setupUi(MainWindow)
MainWindow.show()
sys.exit(app.exec_())
